
name: client CI/CD 

on:
  push:
    paths:
    - "front-end/**"
    branches: [ "main" ]
jobs:
  client:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: build  back-end image
      run: docker compose build ${{secrets.CLIENT_SERVICE}}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: push to Docker Hub
      run: |
         docker tag tour-front-end:${{secrets.CLIENT_TAG}} ${{secrets.DOCKERHUB_USERNAME}}/tour:tour-front-end_v${{secrets.CLIENT_TAG}}
         docker push ${{secrets.DOCKERHUB_USERNAME}}/tour:tour-front-end_v${{secrets.CLIENT_TAG}}
    env:
      SERVER_SERVICE: ${{secrets.SERVER_SERVICE}}
      CLIENT_SERVICE: ${{secrets.CLIENT_SERVICE}}
      CLIENT_TAG: ${{secrets.CLIENT_TAG}}
      CLIENT_PORT: ${{secrets.CLIENT_PORT}}
 
     

  
