version: "3"
services:
  # database
  mysqldb:
    image: mysql:${DATABASE_TAG}
    container_name:  ${DATABASE_SERVICE}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - tour-server-net
    volumes:
      - tour-storage:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_PASSWORD: ${PASSWORD}
  # back-end 
  tour-server:
    build:
      context: ./back-end
      args:
        - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
        - JWT_ACCESS_TOKEN_PERIOD=${JWT_ACCESS_TOKEN_PERIOD}
        - JWT_REFRESH_TOKEN_PERIOD=${JWT_REFRESH_TOKEN_PERIOD}
        - DEFAULT_ROLE=${DEFAULT_ROLE}
        - DEFAULT_PERMISSIONS=${DEFAULT_PERMISSIONS}
        - DEFAULT_USER=${TOUR_MANAGER}
        - APP=${APP}
        - ADDRESS=${ADDRESS}
        - SOCIALS=${SOCIALS}
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - MAIL_PROTOCOL=${MAIL_PROTOCOL}
        - VERIFICATION_EXPIRE_TIME=${VERIFICATION_EXPIRE_TIME}
        - MAIL_REGISTER_DETAILS=${MAIL_REGISTER_DETAILS}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_PASSWORD_DETAILS=${MAIL_PASSWORD_DETAILS}
        - PASSWORD_EXPIRATION=${PASSWORD_EXPIRATION}
    image: tour-back-end:${SERVER_TAG}
    container_name: ${SERVER_SERVICE}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - tour-server-net
      - tour-client-net
    restart: on-failure
    expose:
     - ${SERVER_PORT}
    environment:
      HOST_API: ${BASE_URL}
      DATABASE_PORT: ${DATABASE_PORT}
      SPRING_DATASOURCE_USERNAME: ${TOUR_USER}
      SPRING_DATASOURCE_PASSWORD: ${PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PROTOCOL: ${MAIL_PROTOCOL}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_PASSWORD_DETAILS: ${MAIL_PASSWORD_DETAILS}
      PASSWORD_EXPIRATION: ${PASSWORD_EXPIRATION}
    depends_on:
      - mysqldb

 # Frontend Service
  tour-client:
    build:
      context: ./front-end
    container_name: ${CLIENT_SERVICE}
    image: tour-front-end:${CLIENT_TAG}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    depends_on:
      - ${SERVER_SERVICE}
    networks:
      - tour-client-net
    restart: on-failure
networks:
  tour-server-net:
  tour-client-net:
volumes:
  tour-storage:
