# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: install back-end
      run: mvn -B  package --file back-end/pom.xml
    - name: build  back-end image
      run: docker-compose -f "docker-compose.yml"  -d --build tour-server
    - name: copy target directory
      run: mkdir staging && cp target/* staging
     # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
    env:
      TOUR_USER: ${{secrets.TOUR_USER}}
      PASSWORD: ${{secrets.PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_SERVICE: ${{secrets.DATABASE_SERVICE}}
      SERVER_SERVICE: ${{secrets.SERVER_SERVICE}}
      CLIENT_SERVICE: ${{secrets.CLIENT_SERVICE}}
      DATABASE_TAG: ${{secrets.DATABASE_TAG}}
      SERVER_TAG: ${{secrets.SERVER_TAG}}
      CLIENT_TAG: ${{secrets.CLIENT_TAG}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      SERVER_PORT: ${{secrets.SERVER_PORT}}
      CLIENT_PORT: ${{secrets.CLIENT_PORT}}
      BASE_URL: ${{secrets.BASE_URL}}
      JWT_SIGNING_KEY: ${{secrets.JWT_SIGNING_KEY}}
      JWT_ACCESS_TOKEN_PERIOD: ${{secrets.JWT_ACCESS_TOKEN_PERIOD}}
      JWT_REFRESH_TOKEN_PERIOD: ${{secrets.JWT_REFRESH_TOKEN_PERIOD}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      DEFAULT_ROLE: ${{secrets.DEFAULT_ROLE}}
      DEFAULT_PERMISSIONS: ${{secrets.DEFAULT_PERMISSIONS}}
      EMAIL: ${{secrets.EMAIL}}
      TOUR_MANAGER: ${{secrets.TOUR_MANAGER}}
      LOGO: ${{secrets.LOGO}}
      ABOUT: ${{secrets.ABOUT}}
      PHONE: ${{secrets.PHONE}}
      ADDRESS: ${{secrets.ADDRESS}}
      SOCIALS: ${{secrets.SOCIALS}}
      NAME: ${{secrets.NAME}}
      APP: ${{secrets.APP}}
   
