
name: server CI/CD 

on:
  push:
    paths:
    - "back-end/**"
    branches: [ "main" ]
jobs:
  server:
    name: Job for 'back-end' folder
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: install back-end
      run: mvn -B  install --file back-end/pom.xml
    - name: build  back-end image
      run: docker compose build  ${{secrets.SERVER_SERVICE}}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: push to Docker Hub
      run: |
         docker tag tour-back-end:${{secrets.SERVER_TAG}} ${{secrets.DOCKERHUB_USERNAME}}/tour:tour-back-end_v${{secrets.SERVER_TAG}}
         docker push ${{secrets.DOCKERHUB_USERNAME}}/tour:tour-back-end_v${{secrets.SERVER_TAG}}
    env:
      TOUR_USER: ${{secrets.TOUR_USER}}
      PASSWORD: ${{secrets.PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_HOST_NAME: ${{secrets.DATABASE_HOST_NAME}}
      MYSQL_USER: ${{secrets.MYSQL_USER}}
      MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      DATABASE_SERVICE: ${{secrets.DATABASE_SERVICE}}
      SERVER_SERVICE: ${{secrets.SERVER_SERVICE}}
      CLIENT_SERVICE: ${{secrets.CLIENT_SERVICE}}
      CLIENT_TAG: ${{secrets.CLIENT_TAG}}
      CLIENT_PORT: ${{secrets.CLIENT_PORT}}
      DATABASE_TAG: ${{secrets.DATABASE_TAG}}
      SERVER_TAG: ${{secrets.SERVER_TAG}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      SERVER_PORT: ${{secrets.SERVER_PORT}}
      BASE_URL: ${{secrets.BASE_URL}}
      JWT_SIGNING_KEY: ${{secrets.JWT_SIGNING_KEY}}
      JWT_ACCESS_TOKEN_PERIOD: ${{secrets.JWT_ACCESS_ACCESSTOKEN_PERIOD}}
      JWT_REFRESH_TOKEN_PERIOD: ${{secrets.JWT_REFRESH_ACCESSTOKEN_PERIOD}}
      DEFAULT_USER: ${{secrets.DEFAULT_USER}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      DEFAULT_ROLE: ${{secrets.ROLE_DEFAULT_NAMES}}
      DEFAULT_PERMISSIONS: ${{secrets.PERMISSION_DEFAULT_NAMES}}
      EMAIL: ${{secrets.EMAIL}}
      TOUR_MANAGER: ${{secrets.TOUR_MANAGER}}
      LOGO: ${{secrets.LOGO}}
      ABOUT: ${{secrets.ABOUT}}
      PHONE: ${{secrets.PHONE}}
      ADDRESS: ${{secrets.ADDRESS}}
      SOCIALS: ${{secrets.SOCIALS}}
      NAME: ${{secrets.NAME}}
      APP: ${{secrets.APP}}
      MAIL_HOST: ${{secrets.MAIL_HOST}}
      MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      MAIL_PROTOCOL: ${{secrets.MAIL_PROTOCOL}}
      MAIL_PORT: ${{secrets.MAIL_PORT}}
      VERIFICATION_EXPIRE_TIME: ${{secrets.VERIFICATION_EXPIRE_TIME}}
      REGISTER_CONTENT: ${{secrets.REGISTER_CONTENT}}
      MAIL_REGISTER_DETAILS: ${{secrets.MAIL_REGISTER_DETAILS}}
      PASSWORD_EXPIRATION: ${{secrets.VERIFICATION_EXPIRE_TIME}}
      PASSWORD_RESET_CONTENT: ${{secrets.PASSWORD_RESET_CONTENT}}
      MAIL_PASSWORD_DETAILS: ${{secrets.HOST_PASSWORD_RESET_MAIL}}
      spring.mail.host: ${{secrets.MAIL_HOST}}
      spring.mail.username: ${{secrets.MAIL_USERNAME}}
      spring.mail.password:  ${{secrets.MAIL_PASSWORD}}
      spring.mail.properties.mail.transport.protocol: ${{secrets.MAIL_PROTOCOL}}
      jwt.signing.key: ${{secrets.JWT_SIGNING_KEY}}
      role.default.names: ${{secrets.ROLE_DEFAULT_NAMES}}
      permission.default.names: ${{secrets.DEFAULT_PERMISSIONS}}
      user.default.user: ${{secrets.DEFAULT_USER}}
      jwt.access.accessToken.period: ${{secrets.JWT_ACCESS_TOKEN_PERIOD}}
      jwt.refresh.accessToken.period: ${{secrets.JWT_REFRESH_TOKEN_PERIOD}}
      app.details: ${{secrets.APP}}
      app.address: ${{secrets.ADDRESS}}
      app.socials: ${{secrets.SOCIALS}}
      mail.host: ${{secrets.MAIL_HOST}}
      mail.password: ${{secrets.MAIL_PASSWORD}}
      mail.username: ${{secrets.MAIL_USERNAME}}
      mail.protocol: ${{secrets.MAIL_PROTOCOL}}
      mail.port: ${{secrets.MAIL_PORT}}
      verification.expire.time: ${{secrets.VERIFICATION_EXPIRE_TIME}}
      host.registration.mail: ${{secrets.MAIL_REGISTER_DETAILS}}
      password.reset.expire.time: ${{secrets.PASSWORD_EXPIRATION}}
      host.password.reset.mail: ${{secrets.MAIL_PASSWORD_DETAILS}}
